config/routes.rb
Robots::Application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => 'login',
                                      :sign_out => 'logout', :password => 'secret',
                                      :confirmation => 'verification', :unlock => 'unblock',
                                      :registration => 'register' }

  resources :robots

  resources :relationships, :only => [:create, :destroy]

  resources :microposts, :only => [:create, :destroy]

  root :to => "pages#home"

end

app/models/micropost.rb
# This class was adapted from the example in Ruby on Rails Tutorial by Michael Hartl which
# can be found at http://ruby.railstutorial.org/ruby-on-rails-tutorial-book.

class Micropost < ActiveRecord::Base
  attr_accessible :content

  belongs_to :robot

  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :robot_id, :presence => true

  default_scope :order => 'microposts.created_at DESC'

end

app/models/relationship.rb
# This class was adapted from the example in Ruby on Rails Tutorial by Michael Hartl which
# can be found at http://ruby.railstutorial.org/ruby-on-rails-tutorial-book.

class Relationship < ActiveRecord::Base
  attr_accessible :trackee_id, :tracker_id

  belongs_to :trackee, :class_name => "Robot"
  belongs_to :tracker, :class_name => "User"

  validates :trackee_id, :presence => true
  validates :tracker_id, :presence => true
end

app/models/robot.rb
class Robot < ActiveRecord::Base

  attr_accessible :user_id, :name, :model, :description, :hardware, :software, :applications

  validates :name, :presence => true, :length => { :maximum => 50 }

  has_many :microposts, :dependent => :destroy
  belongs_to :user

  has_many :reverse_relationships, :foreign_key => "trackee_id",
                                   :class_name => "Relationship",
                                   :dependent => :destroy

  has_many :trackers, :through => :reverse_relationships

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  validates :name,  :length => { :maximum => 50 }
  validates :email, :presence => true

  has_many :robots, :dependent => :destroy

  has_many :relationships, :foreign_key => "tracker_id",
                           :dependent => :destroy

  has_many :tracking, :through => :relationships, :source => :trackee

  # The following lines of code were adapted from the example in Ruby on Rails Tutorial
  # by Michael Hartl which can be found at
  # http://ruby.railstutorial.org/ruby-on-rails-tutorial-book.

  def tracking?(trackee)
    relationships.find_by_trackee_id(trackee)
  end

  def track!(trackee)
    relationships.create!(:trackee_id => trackee.id)
  end

  def untrack!(trackee)
    relationships.find_by_trackee_id(trackee).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/microposts_controller.rb
# This class was adapted from the example in Ruby on Rails Tutorial by Michael Hartl which
# can be found at http://ruby.railstutorial.org/ruby-on-rails-tutorial-book.

class MicropostsController < ApplicationController

  def create
    @robot =  Robot.find(session[:current_robot_id])
    @micropost  = @robot.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Robot status updated!"
    else
      flash[:success] = "Robot status could could not be updated!"
    end
    redirect_to @robot
  end

  def destroy
    @robot =  Robot.find(session[:current_robot_id])
    @micropost = @robot.microposts.find(params[:id])
    @micropost.destroy
    redirect_to @robot
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!, :except => []

  def home
    @user = current_user
    @robots = Robot.find(:all,:conditions => {:user_id => current_user.id})
    @relationships = Relationship.find(:all, :conditions => {:tracker_id => current_user.id})
  end

end

app/controllers/relationships_controller.rb
# This class was adapted from the example in Ruby on Rails Tutorial by Michael Hartl which
# can be found at http://ruby.railstutorial.org/ruby-on-rails-tutorial-book.

class RelationshipsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @robot = Robot.find(params[:relationship][:trackee_id])
    current_user.track!(@robot)
    respond_to do |format|
      format.html {redirect_to @robot}
      format.js
    end
  end

  def destroy
    @robot = Relationship.find(params[:id]).trackee
    current_user.untrack!(@robot)
    respond_to do |format|
      format.html {redirect_to @robot}
      format.js
    end
  end

end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /robots
  # GET /robots.xml
  def index
    @robots = Robot.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @robots }
    end
  end

  # GET /robots/1
  # GET /robots/1.xml
  def show
    session[:current_robot_id] = nil
    @micropost = Micropost.new
    @robot = Robot.find(params[:id])
    session[:current_robot_id] = @robot.id
    @microposts = @robot.microposts.paginate(:page => params[:page])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @robot }
    end
  end

  # GET /robots/new
  # GET /robots/new.xml
  def new
    @robot = Robot.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @robot }
    end
  end

  # GET /robots/1/edit
  def edit
    @robot = Robot.find(params[:id])
  end

  # POST /robots
  # POST /robots.xml
  def create
    @robot = Robot.new(params[:robot])

    respond_to do |format|
      if @robot.save
        @robot.update_attribute(:user_id, current_user.id)
        format.html { redirect_to(@robot, :notice => 'Robot was successfully created.') }
        format.xml  { render :xml => @robot, :status => :created, :location => @robot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @robot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /robots/1
  # PUT /robots/1.xml
  def update
    @robot = Robot.find(params[:id])

    respond_to do |format|
      if @robot.update_attributes(params[:robot])
        format.html { redirect_to(@robot, :notice => 'Robot was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @robot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1
  # DELETE /robots/1.xml
  def destroy
    @robot = Robot.find(params[:id])
    @robot.destroy

    respond_to do |format|
      format.html { redirect_to(root_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <i>Powered</i> by &copy;Sion
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="topbar">
    <div class="fill">
      <div class="container">
        <%= link_to "RoboTracker", root_path, :class => "brand" %>
        <ul class="nav">
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>
            <%= link_to "Robots", robots_path %>
          </li>
          <li>
            <% if user_signed_in? %>
                <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
            <% else %>
                <%= link_to "Login", new_user_session_path %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoboTracker</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <!--<link type="text/css" href="css/jquery-ui-1.8.16.custom.css" rel="Stylesheet" />-->
  <!--<script type="text/javascript" src="js/jquery-1.4.4.min.js"></script>-->
  <!--<script type="text/javascript" src="js/jquery-ui-1.8.16.custom.min.js"></script>-->
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container">
  <%= render 'layouts/header' %>
  <div class="content main">
     <% if user_signed_in? %>
      Signed in as <%= current_user.email %>
  <% else %>
      Not a member? It's free to <%= link_to "sign up", new_user_registration_path %>!
  <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <br/>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
  </td>
  <td>
    <%= link_to "delete", micropost, :method => :delete,
                                     :confirm => "Are you sure?",
                                     :title => micropost.content %>
  </td>
</tr>

app/views/microposts/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :robot_id => :id %>
  </div>
<% end %>

app/views/pages/home.html.erb
<table>
  <tr>
    <td>
      <h3>My Robots</h3>
    </td>
  </tr>
  <% @robots.each do |robot| %>
  <tr>
    <td><%= robot.name %></td>
    <td>
      <%= link_to 'View page', robot %> |
      <%= link_to 'Edit', edit_robot_path(robot) %> |
      <%= link_to 'Delete', robot, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
  <% end %>
  <tr>
    <td>
    <%= link_to 'New Robot', new_robot_path %>
    </td>
  </tr>
</table>

<br />
<br />

<% if @relationships.count > 0 %>
  <table>
    <tr>
      <td>
        <h3>Robots I'm tracking</h3>
      </td>
    </tr>
    <% @relationships.each do |relationship| %>
    <tr>
      <td><%= relationship.trackee.name %>
      (owned by <i><%= relationship.trackee.user.email %></i>)</td>
      <td><%= link_to 'View page', relationship.trackee %></td>
    </tr>
    <% end %>
</table>
<% end %>

app/views/relationships/create.js.erb
$("#track_form").html("<%= escape_javascript(render('robots/untrack')) %>")

app/views/relationships/destroy.js.erb
$("#track_form").html("<%= escape_javascript(render('robots/track')) %>")

app/views/robots/_form.html.erb
<%= form_for(@robot) do |f| %>
  <% if @robot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@robot.errors.count, "error") %> prohibited this robot from being saved:</h2>

      <ul>
      <% @robot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :hardware %><br />
    <%= f.text_field :hardware %>
  </div>
  <div class="field">
    <%= f.label :software %><br />
    <%= f.text_field :software %>
  </div>
  <div class="field">
    <%= f.label :applications %><br />
    <%= f.text_field :applications %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/robots/_track.html.erb
<%= form_for current_user.relationships.
                          build(:trackee_id => @robot.id),:remote => true do |f| %>
  <div><%= f.hidden_field :trackee_id %></div>
  <div class="actions"><%= f.submit "Track robot" %></div>
<% end %>

app/views/robots/_track_form.html.erb
<div id="track_form">
  <% if current_user.tracking?(@robot) %>
    <%= render 'untrack' %>
  <% else %>
    <%= render 'track' %>
  <% end %>
</div>

app/views/robots/_untrack.html.erb
<%= form_for current_user.relationships.find_by_trackee_id(@robot.id),
             :html => { :method => :delete }, :remote => true do |f| %>
  <div class="actions"><%= f.submit "Stop tracking" %></div>
<% end %>

app/views/robots/edit.html.erb
<h1>Editing robot</h1>

<%= render 'form' %>

<%= link_to 'Show', @robot %> |
<%= link_to 'Back', root_path %>

app/views/robots/index.html.erb
<table>
  <tr>
    <td>
      <h3>All Robots</h3>
    </td>
  </tr>
  <tr>
    <th>Name</th>
    <th>Owner</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @robots.each do |robot| %>
  <tr>
    <td><%= robot.name %></td>
    <td><%= robot.user.email %></td>
    <td><%= link_to 'View page', robot %> |
    <% if current_user == robot.user%>
      <%= link_to 'Edit', edit_robot_path(robot) %> |
      <%= link_to 'Delete', robot, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
    </tr>
<% end %>
</table>

app/views/robots/new.html.erb
<h1>New robot</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/robots/show.html.erb
<table>
    <tr>
      <td><b>Robot:</b></td>
      <td><%= @robot.name %></td>
    </tr>

    <tr>
      <td><b>Model:</b></td>
      <td><%= @robot.model %></td>
    </tr>

    <tr>
      <td><b>Description:</b></td>
      <td><%= @robot.description %></td>
    </tr>

    <tr>
      <td><b>Hardware:</b></td>
      <td><%= @robot.hardware %></td>
    </tr>

    <tr>
      <td><b>Software:</b></td>
      <td><%= @robot.software %></td>
    </tr>

    <tr>
      <td><b>Applications:</b></td>
      <td><%= @robot.applications %></td>
    </tr>
    <% if current_user == @robot.user %>
    <tr>
      <td>
        <p>
          <%= link_to 'Edit', edit_robot_path(@robot) %> |
          <%= link_to 'Back', root_path %>
        </p>
      </td>
    </tr>
    <% else %>
      <tr>
        <td>
            <p>
              <%= render 'track_form' if signed_in? %>
            </p>
        </td>
    </tr>
    <% end %>
</table>
<% if current_user == @robot.user %>
  <table>
   <tr>
     <td><p>Make a new roblog entry...<p></td>
   </tr>
   <tr>
     <td><%=render 'microposts/micropost_form'%></td>
   </tr>
  </table>
<% end %>

<% unless @robot.microposts.empty? %>
  <table class="microposts" summary="Robot microposts">
     <%= render @microposts %>
   </table>
   <%= will_paginate @microposts %>
<% end %>